//@flow

export const pubsubConfig = {
  RETAILER_CREATED: "RETAILER_CREATED",
  RETAILER_UPDATE_PROFILE: "RETAILER_UPDATE_PROFILE",
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
};
